Create README.md
sp614x/optifine pull request #6506
Opened 2021-12-24 03:08 UTC by frogweezer

2022-03-22 18:17 UTC, MrCheeze446 commented
A few suggestions: 

- Combine AA and AF under one entry, the two features are similar enough to be listed under one.
- remove fast texture pack switching (old, no longer exists)
- remove time control (old, no longer exists)
- remove autosave (you get the idea)
- remove fullscreen resolution, this has been a Minecraft feature for a long time now
- remove mention of HD textures and fonts, this was added by Minecraft
- remove mention of Vsync, this is vanilla now
- clear water was added in 1.13, probably specify this
- specify that OptiFine just adds buttons for toggle the debugging features such as lagometer, debug profiler, and advanced tooltips
- MCForum is essentially dead at this point, there isn't really any harm in keeping it but I'd personally remove it
- combine Better Grass, Better Snow, Random Mobs, Connected Textures, and Natural textures under one bullet, have each feature listed be its own sub-bullet.

I could be wrong with some of these features I suggest to remove mention of, I'd let sp look over this and confirm what is or is not correct about this.

2022-03-31 17:06 UTC, vinc3nz commented
Looks nice!
Suggestion:
- Add a message, that this repo is not Optfine Sourceode.
- Add the Website (optifine.net) and the Backup Website (optifined.net)

2022-04-22 15:33 UTC, RaptaG commented
Line 86, `)` is placed at a wrong place, making it part of the link..

2022-04-22 15:35 UTC, Ari-RERA-43 commented
Since Fast fog has been removed, it might be a good idea to remove that to prevent confusion.

2022-06-11 10:53 UTC, ooliver1 requested changes

2022-06-11 10:53 UTC, ooliver1 commented on .gitignore
> +.DS_Store
Unrelated, place this in your global gitignore file

2022-06-11 10:53 UTC, ooliver1 commented on README.md
> +  **[Donate to OptiFine](https://optifine.net/donate)** and receive the [OptiFine cape](http://i.imgur.com/zXIkv.png) as a sign of your awesomeness. Capes are visible to everyone using OptiFine. Than
Bolded text should just go in []

2022-06-11 10:53 UTC, ooliver1 commented on README.md
> +  <br>
Why not use other non-html methods for line breaks

2022-07-26 16:35 UTC, TheKodeToad commented
Some text mentioning that this repo is primarily for issue tracking and docs would also be nice.

2022-08-25 07:36 UTC, closed without merging